site_name: Hexkit Documentation
site_description: Comprehensive documentation for the hexkit library
site_url: https://ghga-de.github.io/hexkit/

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - yaml
    - json
    - bash

nav:
  - Home: index.md
  - Architectural Concepts:
    - arch_concepts/overview.md
    - Hexagonal Architecture: arch_concepts/hexagonal_arch.md
    - Triple Hexagonal Architecture: arch_concepts/triple_hexagonal_arch.md
    - Event-Driven Architecture: arch_concepts/event_driven_arch.md
    - Dead Letter Queue: arch_concepts/dlq.md
  - Protocols:
    - protocols/overview.md
  - Providers:
    - providers/overview.md
    - Kafka:
      - providers/kafka/publisher.md
      - providers/kafka/subscriber.md
      - providers/kafka/test_utils.md
    - MongoDB:
      - providers/mongodb/dao.md
      - providers/mongodb/migration_tools.md
      - providers/mongodb/test_utils.md
    - MongoKafka:
      - providers/mongokafka/outbox_pub.md
      - providers/mongokafka/persistent_publisher.md
    - S3:
      - providers/s3/overview.md
      - providers/s3/test_utils.md
  - Observability Tools:
    - observability_tools/overview.md
    - observability_tools/correlation_ids.md
    - observability_tools/logging.md
  - Developer Help:
    - developer_help/overview.md
    - developer_help/testing.md
    - developer_help/outbox_v_persistent_pub.md
  - Structure:
    - structure/overview.md
  - API Reference: api/
  - Glossary:
    - glossary/index.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - tables
  - fenced_code

plugins:
  - search
  - mkdocs-autoapi:
      autoapi_dir: src
      autoapi_ignore:
        - "**/tests/**"
        - "**/examples/**"
      autoapi_add_nav_entry: false
      autoapi_keep_files: true
      autoapi_root: api
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
          options:
            members: true
            inherited_members: true
            show_bases: true
            show_source: false
            preload_modules:
              - pydantic
            extensions:
              - griffe_pydantic:
                  schema: true
