name: Static Code Analysis

on: push

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    name: Static Code Analysis
    steps:
      - uses: actions/checkout@v3

      - id: common
        uses: ghga-de/gh-action-common@v4

      - uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch
      - name: ruff
        run: |
          ruff check --output-format=github .
          ruff format --check .
      - name: mypy
        run: |
          mypy .
      - name: Check license header and file
        run: |
          ./scripts/license_checker.py
