name: Unit and Integration Tests

on: push

jobs:
  unit_and_int_tests:
    runs-on: ubuntu-latest
    name: Unit and Integration Tests

    steps:
      - uses: actions/checkout@v3

      - id: common
        uses: ghga-de/gh-action-common@v1.0.3

      - name: Run pytest
        run: |
          export ${{ steps.common.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.common.outputs.CONFIG_YAML }}"
          pytest \
            --cov="${{ steps.common.outputs.MAIN_SRC_DIR }}" \
            --cov-report=xml

      - id: coveralls
        name: Upload coverage to coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install --upgrade coveralls
          coveralls --service=github
